### ISSUE TITLE
Proposal: add clear copyright statement

### ISSUE THREAD

**Issue by tngraf** [angular-translate/bower-angular-translate-loader-partial#18]
I'm working at a large company in a team that evaluates third party software for its use in their products.
According to our lawyers a copyright statement like 'Copyright (c) 2015' is more or less useless because you need a person or an organization that owns the copyright.

Proposal: use either a contributor name or something like 
'Copyright (c) 2015 angular translate loader partial team'

Cheers,
Thomas

**Comment by tspaeth** [comment]
Hi!

This is only a bower repo. Please file issues and questions in the main repo at 
https://github.com/angular-translate/angular-translate/issues

But anyway, if you look at the main license file itself https://github.com/angular-translate/angular-translate/blob/master/LICENSE you'll see that Pascal is currently mentioned there as the copyright holder. 
Personal remark: The large companies I work with are totally fine with this license files.
But yes, maybe we should align all headers in the sourcecode also.
