### ISSUE TITLE
Incorrect license declaration in bower.json

### ISSUE THREAD

**Issue by gjdev** [angular-translate/bower-angular-translate-loader-partial#19]
According to the bower.json spec, the declaration of licenses should be in a field named "license" (see http://bower.io/docs/creating-packages/#license). This packages names the field "licenses" instead. Could "licenses" be changed to "license". Also the field should be an array of strings, not an array of objects. The current declaration makes it impossible to digest the license information with other tools. (We need that for automatic generation of webjars (http://webjars.org) from the bower package, for use in java applications).

**Comment by knalli** [comment]
Hm, that's the same as in package.json actually. Okay, should be fixed in all bower.json files...
